### ISSUE TITLE
STEPPER_BUZZ - chyba v textu

### ISSUE THREAD

**Issue by Kowy54** [PavelTajdus/Voron-cz-guide#8]
"The STEPPER_BUZZ command will cause the given stepper to move one millimeter in a positive direction and then it will return to its starting position." Nikde zde nepíšou o 10mm jak uvádíte ve svém návodu.

**Comment by PavelTajdus** [comment]
Díky za připomínku. Opravím. Ono asi došlo k nějakým změnám, protože motory se hýbaly dříve více než 1 mm. Opravíme. Každopádně na účel téhle kontroly to nemá vliv.

**Comment by PavelTajdus** [comment]
Upraveno.
